name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: wine install
        run: |
          sudo dpkg --add-architecture i386
          wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
          sudo apt update
          sudo apt install --install-recommends winehq-stable
      - name: npm install, build
        run: |
          cd application
          rm -rf dist/
          npm install -g @quasar/cli yarn --force
          yarn install
          quasar build --mode electron --publish -T win32 
          quasar build --mode electron --publish -T win 
          quasar build --mode electron --publish -T linux
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-upload
          path: |
            application/dist