name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: wine install
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine32
      - name: npm install, build
        run: |
          cd application
          rm -rf dist/
          npm install -g @quasar/cli yarn --force
          yarn install
          quasar build --mode electron --publish always -T win
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-upload
          path: |
            application/dist
      - name: npm install, build
        run: |
          cd application
          quasar build --mode electron --publish always -T linux
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-upload
          path: |
            application/dist