name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install, build
        run: |
          cd application
          npm install -g @quasar/cli yarn --force
          npm install
          quasar build --mode electron
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-upload
          path: |
            application/dist